version: '3.9'
services:
  etl:
    # TODO: Add your ETL Dockerfile
    build:
      context: .
    depends_on:
      - postgres
    env_file: .env
    networks:
      - backend

  postgres:
    # TODO: Add PostgreSQL 15
    image: postgres:15.4
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  backend:
    driver: bridge
